name: CICD
# continous delivery
on:
# When user runs, manual click (deliver) workflow.
  workflow_dispatch:

jobs:
# Parellelism - every jobs need seprate runner.
  code:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout code
        run: echo "code clone form Github"
  
  build: 
      runs-on: ubuntu-latest
      steps:
        - name: Build Docker container
          run: echo "Docker Container build"
  
  test:
        needs: build
        runs-on: ubuntu-latest
        steps:
          - name: Test the container
            run: echo "Testing the container" 

  deploy:
    needs: [test, build]
    runs-on: ubuntu-latest
    steps:
      - name: Deploying the app
        run: echo "Docker compose deployed the app"
          
        
          
  
    
    
